### ISSUE TITLE
Scrolling issue (whole page scrolls)

### ISSUE THREAD

**Issue by hobe** [mcasimir/mobile-angular-ui#192]
If you scroll up immediately after page load (scrollTop of scrollable-content div =0), the whole page (including the header navbar) scrolls up instead of the scrollable-content div!
When you scroll down (while the whole page bounces back to top) it is also possible to scroll the whole page down (including the footer bar).

If you first scroll down a bit and then scroll to the top of the page again, it seems to work, because then only the scrollable-content div scrolls and the navbar header stays on top.

Is it possible to prevent the "whole page" bouncing?  (like kendo does: http://demos.telerik.com/kendo-ui/mobile-listview/index - header bar is always on top)

You can reproduce this issue on your demo page!
Screenshots: http://1drv.ms/1K61Arg

I need this because I want to implement a pull-to-refresh list (using https://github.com/mgcrea/angular-pull-to-refresh), but it does not work if the user immediately wants to refresh (scroll page up) without scrolling down first. 

As a workaround a currently set the value of the scrollTop property to 1 after the view gets activated (but it only works once, if user scrolls back to top (scrollTop=0) it will stop working):
```
$timeout(function () {
   var scrollableElement = $('#scrollableContainer')[0];
   scrollableElement.scrollTop = 1;
}, 10);
```

User-Agent
Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B440 Safari/600.1.4

**Comment by mcasimir** [comment]
Hi, i'm working on it right now since the next release will be all about gestures.

A quick fix in the meanwhile would be to prevent default for `touchmove` once `scrollTop` or `scrollDown` is reached. Not tried yet.

Anyway a more generic solution is in progress.

If you're planning to build a Phonegap/Cordova app you can prevent this behaviour through cordova config.

I will be really happy to have a little help in fixing this. 
Thank you anyway!

**Comment by hobe** [comment]
Thanks for your quick reply!
I'm working on a PhoneGap app, so the DisallowOverscroll config property works for me. Thank you for the great hint!
