### ISSUE TITLE
Overlays only viewable once

### ISSUE THREAD

**Issue by nirium** [mcasimir/mobile-angular-ui#206]
Hi,

Yet another overlay problem. I have overlays everywhere in the application and two of them are located in the right sidebar aswell as in a template further down in the right sidebar (ng-include).

When I start/reload the application the overlays get registered but as soon as I change a page in the left sidebar they will never ever be registered again.

Any ideas?

**Comment by nirium** [comment]
Although, I think I don't need to have them in different places anymore. I'll investigate a bit more and see what I come up with

**Comment by nirium** [comment]
Ok, I really need a solution here...

I want to be able to show my modals from enywhere in the application. I don't want them to be page specific. I want the effect like version 1.1 where you just call them and they appear. How can I ensure that if I call a modal/overlay that it will 100% show up wherever I am in the application?

**Comment by mcasimir** [comment]
Just put it outside ng-view and ui-content-for, and they will be always available.

**Comment by nirium** [comment]
Can you be more specific?

In my index file right before the closing </body> I have the yield-to stuff.

Where do I put all the content for and modal content?

So if you called ui-turn-on="modal1" on your accordion page, the modal in overlay.html would actually show?

**Comment by mcasimir** [comment]
I think maybe you misunderstood the `content-for/yield-to` stuffs, modals have nothing to do with them. If you don't want to populate a layout element with view specific contents you don't need them.

So just put your `modal` markup without `content-for`/`yield-to` after the `yield-to` stuffs. and everithing should be fine.

Can I ask you a favor?

Since your perspective seems to be more neutral than mine, could you try to edit: https://github.com/mcasimir/mobile-angular-ui-website/blob/master/contents/components/modals.md
To explain those stuffs.

I think I'm too much into this to write an easy to understand documentation, so I forgot basic things like how to create a global modal.

Thank you anyway.

**Comment by nirium** [comment]
Wow, incredible... Haha such a waste :D I'm a bit busy right now but I might get my hands on it later tonight. I think the problem is that the documentation and source code almost implies that it's required to use yield-to/content-for. But it might be my lack of understanding of them that makes this a completely useless issue :)

Thanks again for the replies!
