### ISSUE TITLE
npm version support

### ISSUE THREAD

**Issue by evermax** [mcasimir/mobile-angular-ui#289]
Hi!
On npm the version is 0.0.0. cf https://www.npmjs.com/package/mobile-angular-ui
Apparently you need to publish the versions by hand using `npm publish`.
It would be really helpful if you could publish one of the latest versions of your project.
I am moving from bower to npm to handle the dependencies of my projects, and I would like to keep using it!

Have a nice evening!

**Comment by mcasimir** [comment]
Hi @evermax,
I attempted to publish 1.2 on npm in the past days but i noticed currently the npm package is not under my ownership. 

It has been published without approval by someone else directly from this repo, that makes me think it  was done without  bad intentions, maybe who done this just needed it, but now i don't have control over it. I've requested a transfer and signaled that to npmjs support.

I'm waiting response since, among making last releases awailable through npm, i wish to merge the generator with this repo in order to create a binary, something like:

``` sh
> npm -g mobile-angular-ui

> mobile-angular-ui new MyApp
```

**Comment by evermax** [comment]
I see, that is unfortunate! I hope it will be solved soon :smile:
Do you have any feedback from npmjs on how long it might take? Just to know if I wait or try a workaround with using back bower.
Meanwhile, have a nice evening, thanks for the update and your work on the project, it is very handy!
Cheers.

**Comment by rikiscripts** [comment]
You mean npm install -g mobile-angular-ui or npm i -g mobile-angular-ui right?

**Comment by mcasimir** [comment]
Right thanks!

**Comment by evermax** [comment]
In your `package.json`, the main file is supposed to be `index.js`, but it doesn't exist. For this to work with browserify and npm, I would advice to put `dist/js/mobile-angular-ui.js` instead as `main`.
So the `require()` directive will know which file to import!

**Comment by felixruponen** [comment]
+1 I would like this to work without bower as a dependency for my project. (I use webpack)

**Comment by mcasimir** [comment]
Hi guys npm support answered they will move ownership to me in a few weeks. In the meanwhile i'll do as @evermax suggested. Please be patient or just use git url in your package.json to specify the right dependency.

Sorry for the inconvenience.

**Comment by evermax** [comment]
That is good news!
No worries, thanks for letting us know @mcasimir. I will just use bower a little more :)
