### ISSUE TITLE
Dumbfounded about weird behaviour on input fields

### ISSUE THREAD

**Issue by NicTorgersen** [mcasimir/mobile-angular-ui#375]
Hi,

I have a mobileangularui project, and because of unspecified and badly documented behaviour with this library I'm stuck.

I have a modal I'm opening on one page, together with an unrelated input field. The modal window is initialized within my class="app" (which seems to be a problem, so I can't use the overlay functionality), as well as input type (atleast for text) fields get the INLINE STYLING "pointer-events: none;".

Anyone know why this happens, and is this project dead?

**Comment by mcasimir** [comment]
Hi nic, I'll answer your question tomorrow. Last commit has been made today, so the project is not dead.

**Comment by mcasimir** [comment]
Ok here I am. I've added docs and question label for now.

You're are right you should not include a modal inside `.app`,  otherwise you'll experience misbehaviours.

That's due to this style:

``` css
.has-modal, .has-modal-overlay {
  .app, .sidebar {
    pointer-events: none;
  }
}
```

That's  intended since some ms devices where ignoring the overlaying modal and passing touch events to the layers behind.  

As for your case, you have 3 options:
- 1. If its a global modal you can define the modal outside `.app`
- 2. If its a modal local to some view you can copy the demo behaviour and use `yield-to` and `content-for`.

``` html
    ....
    </div><!-- ~ .app -->

    <div ui-yield-to="modals"></div>
```

- 3. If you don't need to target windows devices you may override those rules in your css.

**Comment by mcasimir** [comment]
Closing for now. Feel free to reopen if u need other clarifications.
